### ISSUE TITLE
random pekorat picture that activates when you say "pekorat" with a few minute cooldown

### ISSUE THREAD

**Issue by bemxio** [bemxio/discord-pekofy-bot#10]
requested by u/naNELSONninonu on Reddit

**Comment by valanm22** [comment]
@bemxio should I create a file for this like pekofy.py or add it with emotions.py? Can you give me some instructions on how to do this?

**Comment by bemxio** [comment]
since it's not a command, it should be added into `reactions.py`, more specifically the `on_message` event
please put a keyword for it in `replies.handling` as a variable, so that it can be customizable
i will assign you to this issue now

**Comment by bemxio** [comment]
also don't forget to add it into `replies.docs` for people to know it exists

**Comment by valanm22** [comment]
Sure @bemxio. I'll hit you up if there's an issue.

**Comment by valanm22** [comment]
@bemxio I've added the command. I don't know how to implement the cooldown on `reactions.py`. Moreover could you provide me with some pekorat image links?

**Comment by bemxio** [comment]
@valanm22 let's implement the cooldown as a 1/4 change (like with pain peko)
and you can use these links for the thing:
https://cdn.discordapp.com/attachments/857811318195486740/880255390644850758/rrat.mp4
https://bemxio.s-ul.eu/b2JmwJfD.jpg
