### ISSUE TITLE
!helpeko not working

### ISSUE THREAD

**Issue by Derasiel** [bemxio/discord-pekofy-bot#11]
Basicly title.

When I do the command !helpeko I don't receive anything, but I can trigger every other commands.

![image](https://user-images.githubusercontent.com/37622648/149402530-685605ef-9c4a-4446-b719-511e89d4551a.png)

I also tried to change my account name since it has a special character in it and it's not fixing it.

**Comment by bemxio** [comment]
are you sure you have `Privacy & Safety > Allow direct messages from server members` enabled in the user and/or server settings? it might be that
if it is just that, i will need to either make the command sent its content on a server, or send an error message

**Comment by Derasiel** [comment]
Ah yes it is indeed this. Thank you!

**Comment by bemxio** [comment]
alright, i will make an error handler to avoid issues like these for users :)
