### ISSUE TITLE
fix markdown on !pekopasta texts

### ISSUE THREAD

**Issue by bemxio** [bemxio/discord-pekofy-bot#16]
since asterisks are italic signs on Discord
there's just a need to replace `*` to `\*` onto `replies.pekopasta.sfw`

**Comment by Aadityajoshi151** [comment]
HelIo
I would like to work on this. Before making any kind of change, I just want to confirm the place where the change is to be made which is https://github.com/bemxio/discord-pekofy-bot/blob/main/replies/copypasta.py#L20-#L37 right?

**Comment by bemxio** [comment]
yes, that's exactly the part where it needs to be fixed!
i will assign you to this issue now
