### ISSUE TITLE
pain-peko triggers on "paint" and other words

### ISSUE THREAD

**Issue by bucket3432** [bemxio/discord-pekofy-bot#23]
It appears the bot is not searching for an exact match and is replying with `pain-peko` to any message that contains `pain`, even if it's part of a larger word. I would expect it to reply only if `pain` appears as a word, although I think the original Reddit bot only triggers when the message is exactly equal to the trigger if I understand [this line](https://github.com/emso-c/pekofy-bot/blob/4f691a6bad757e59998819c10d729ec2165863f5/replies.py#L38) and [this line](https://github.com/emso-c/pekofy-bot/blob/4f691a6bad757e59998819c10d729ec2165863f5/main.py#L142) correctly.

### Example: `paint`

![screenshot_2022-02-15_11-28-31](https://user-images.githubusercontent.com/22436557/154105454-b3efa895-7549-4ca0-98ed-d9d1641b155d.png)

### Example: `paineronii`

![screenshot_2022-02-15_11-29-28](https://user-images.githubusercontent.com/22436557/154105470-08130416-e346-4591-b23e-28a1cc9fccda.png)

### Example: `Spain`

![screenshot_2022-02-15_11-31-52](https://user-images.githubusercontent.com/22436557/154105883-3c8bfb91-da7a-44f8-8598-ba9c910260d3.png)

### Example: `repaint`

![screenshot_2022-02-15_11-33-14](https://user-images.githubusercontent.com/22436557/154106131-f6594773-487e-4268-9bb6-67559c8a6db3.png)

**Comment by bemxio** [comment]
alright, i see i see, [line 19](https://github.com/bemxio/discord-pekofy-bot/blob/main/extensions/reactions.py#L19) in `extensions.reactions` checks if any of the triggers from a list are contained in the message content
a simple fix would be to just replace `x in content` to `x == content`
